liip_imagine:
  twig:
    mode: lazy
  filter_sets:
    my_thumb_filter:
      filters:
        thumbnail:
          size: [220, 220]
          mode: outbound
    my_little_filter:
      filters:
        thumbnail:
          size: [60, 60]
          mode: outbound
    my_middle_filter:
      filters:
        thumbnail:
          size: [150, 150]
          mode: outbound
    my_default_filter:
      quality: 75
      filters:
        thumbnail:
          size: [150, 150]
          mode: outbound
    my_icones_filter:
      filters:
        thumbnail:
          size: [32, 32]
          mode: outbound
    my_machines_filter:
      filters:
        thumbnail:
          size: [32, 32]
          mode: outbound
