liip_imagine:
  filter_sets:
    my_thumb_filter:
      filters:
        thumbnail:
          size: [220, 220]
          mode: outbound
    my_little_filter:
      filters:
        thumbnail:
          size: [60, 60]
          mode: outbound
    my_middle_filter:
      filters:
        thumbnail:
          size: [200, 200]
          mode: outbound
    my_default_filter:
      quality: 75
      filters:
        thumbnail:
          size: [210, 210]
          mode: outbound
    my_icones_filter:
      filters:
        thumbnail:
          size: [32, 32]
          mode: outbound
    my_machines_filter:
      quality: 75
      filters:
        thumbnail:
          size: [600, 400]
          mode: outbound